### ISSUE TITLE
C bindings

### ISSUE THREAD

**Issue by mdsitton** [pcwalton/pathfinder#12]
As mentioned quite a few times in the hacker news post from a few days ago the ability to use pathfinder from other languages would be a great addition.

**Comment by pcwalton** [comment]
There are a few C bindings with Pathfinder 2, but they're incomplete. Leaving this open until they become more complete.

**Comment by mdsitton** [comment]
Good to know. I'm still looking forward to using pathfinder in my project once it has matured a bit more :)

**Comment by jpturcotte** [comment]
I would like to know too, please. This is a really nice project!

**Comment by pcwalton** [comment]
The API is still in flux and I haven't gotten around to writing working C bindings yet. If you have a fixed set of paths, however, you can use the offline tool to generate Pathfinder mesh libraries and use them in C++ apps.

**Comment by mdsitton** [comment]
Gotta make sure you don't totally forget about this ;)  Good to know, though i was planning on trying to use it for more generic text rendering so that won't exactly work yet. Thanks!

**Comment by mdsitton** [comment]
2 Years layer, My yearly bump :) Any progress?

**Comment by pcwalton** [comment]
I'm currently working on Pathfinder 3 and the API will need to take some time to settle down before I think about C bindings.

**Comment by crazydef** [comment]
Sadly this project would be far more useful to many more people if it were written in C++ (or at least C) in the first place.  As it stands, as much as I would like to consider it as an option for us, I'm simply not going to even consider investing the time required to implement it due to the language used.

**Comment by whmountains** [comment]
@crazydef @mdsitton you could contribute the bindings yourself if you really need them.  Though I understand that represents an extra time investment which may push you towards other libraries.

**Comment by crazydef** [comment]
To be fair, the C-bindings are the least of my worries.  :)  We need to support all the major platforms out there today (Android, iOS, tvOS, macOS, Windows) - mostly doable with Rust, with a view to supporting additional console platforms in the future - less likely bordering on never-going-to-happen.  To that end we also need Metal, DirectX, and Vulkan support.  OpenGL is only used on Android for us now, and that will be gone within a year, I reckon.

**Comment by whmountains** [comment]
At one point there was some talk about porting pathfinder to the [gfx-rs](https://github.com/gfx-rs/gfx) hardware abstraction layer, which would allow it to support Metal, DirectX, Vulkan, and OpenGL.  I don't know if anything came of that, though.

If you're worried about console support, there was a [Reddit AMA](https://www.reddit.com/r/rust/comments/78bowa/hey_this_is_kyren_from_chucklefish_we_make_and/) a while back where @kyren talked about writing a game engine in Rust.  They said it took about 2 weeks of work to get Rust running on the major consoles, but the target support work couldn't be shared because of NDAs with the console vendors.  If you search for "console" on that page she gives some hints on what was required which you may find useful.

**Comment by pcwalton** [comment]
For what it's worth, Pathfinder 3 has a minimal device abstraction which is designed to abstract away all the OpenGL goop, similar to the one WebRender has. It shouldn't be hard to port it to other GPU APIs; it's a very small set of functionality to begin with.

**Comment by nweston** [comment]
I'm interested in working on this. Any suggestions on where to start, or overall approach?

**Comment by pcwalton** [comment]
Also you might want to consider syncing up with @toolness who has expressed interest in this as well.

**Comment by pcwalton** [comment]
I've now added some basic C bindings. They're incomplete, but let's file issues on missing pieces individually.
