### ISSUE TITLE
Is this ready for production use?

### ISSUE THREAD

**Issue by Xaeroxe** [pcwalton/pathfinder#28]
I'm considering using this project in the [Amethyst](https://github.com/amethyst/amethyst) game engine.  I have a few questions:

In this [issue](https://github.com/pcwalton/pathfinder/issues/15) you state you're working on Pathfinder 2.  How soon can I reasonably expect that to be ready?  Also, will Pathfinder 1 work on Windows 10?  Is it just the example failing or is it the library itself?  What font formats are supported?  Are you planning on uploading this to cargo at any point?

**Comment by Xaeroxe** [comment]
Also would you be opposed to a pull request porting this to gfx?  https://github.com/gfx-rs/gfx

**Comment by pcwalton** [comment]
>  How soon can I reasonably expect that to be ready?

The algorithms are currently basically designed and implemented. There's a lot of grunt work left to do, though: demos, documentation, benchmarks, utilities… I would say perhaps it's a month away, but take that estimate with a huge grain of salt.

>  Also, will Pathfinder 1 work on Windows 10?

Yes, I've tested it there.

>  What font formats are supported?

TrueType/OpenType/WOFF/WOFF2.

>  Are you planning on uploading this to cargo at any point?

Yes.

> Also would you be opposed to a pull request porting this to gfx? 

I wouldn't advise working on Pathfinder 1 right now. (Anything inside `pathfinder-classic/` is PF1, while all other code is PF2.) Pathfinder 2's algorithm is completely different and is vastly improved in every way other than cold-start rendering performance at relatively small font sizes, which doesn't matter because the overhead of loading the font file from disk tends to dominate in these situations anyway.

I plan to delete `pathfinder-classic/` once Pathfinder 2 has fully matured.

Note that Pathfinder 2 is significantly more modular than Pathfinder 1 was. It's best viewed as a series of crates that can be put together to make a text engine, not a text engine itself. Pathfinder 1 attempted to do basic Latin text layout and font reading, but it never really worked right and it's better to use another crate, such as HarfBuzz, for that.

**Comment by daiheitan** [comment]
I can see that in PathFinder 2, Loop-Blinn algorithm is used. Are there any other papers supporting the main idea of pathfinder 2? The partitioner is really confusing for me

**Comment by pcwalton** [comment]
The partitioner is a generalized version of "A Fast Trapezoidation Technique for Planar Polygons", Lorenzetto et al 2002. The main way the algorithm differs from the paper is that Bezier curves are partitioned directly via de Casteljau subdivision, using the quadratic formula to find the intersection of the sweep line with each curve.

**Comment by daiheitan** [comment]
So PF2 uses this algorithm to split a general polygon to trapezoids, and then draw two triangles (or curves) for every trapezoid? Is that correct? BTW, why not use a triangulation algorithm directly?

**Comment by pcwalton** [comment]
In non-antialiased mode and SSAA mode, that's correct. In ECAA mode, it's more complicated, though it still uses the same mesh.

I don't use a triangulation algorithm because:

1. The calculations for ECAA (analytic antialiasing) become a lot simpler when you have trapezoids with horizontal or vertical legs. Clipping a quadrilateral to the pixel square is simpler if the sides are straight.

2. The only triangulation algorithm with comparable time bounds is the monotone polygon partitioning algorithm, which is not easy to generalize to curves, unlike trapezoidation. That algorithm is also difficult to adapt to degenerate and twisted polygons. It might be possible to make triangulation work regardless, which would reduce the number of Steiner vertices, but it would require a lot of work and I don't want to let the perfect be the enemy of the good :)

**Comment by daiheitan** [comment]
Thanks for the explanation. That makes sense

**Comment by pcwalton** [comment]
Closing as I believe all questions here have been answered.
