### ISSUE TITLE
Plans for supported platforms and/or apis?

### ISSUE THREAD

**Issue by duane** [pcwalton/pathfinder#54]
From what I understand, the core algorithms of path rendering have solidified, but the actual interface to Pathfinder is still very much in flux. In addition, I haven't seen any reference to any plans for support beyond mac os, and the (admittedly awesome) demo is split between multiple languages--including, it seems, the entirety of the code loading the data into the shaders.

Anyway, that seems like a pretty specific setup. Are there plans for expanding:

1. The client-side rendering code to a rust-native chunk of code?
2. The shader-side rendering to other platforms (vulkan, metal, v3d, etc)

I'd like to play around with it, but I'm hesitant to where I should invest my efforts.

Best,
Duane

**Comment by pcwalton** [comment]
I wasn't planning on offering a generic Rust client-side renderer, because I couldn't come up with an interface that would satisfy all use cases. For example, in WebRender, Pathfinder needs to be pretty deeply integrated into the engine. Some parts of SVG (e.g. filters) are things that only WR knows how to do. Font rendering needs to integrate with WR's atlas management subsystem. And so forth.

Instead, the idea behind Pathfinder 2 has been to (a) write as much as possible in generic Rust *without* touching a specific graphics API (the server-side code); (b) provide standalone shaders that you can use in your app however you wish. That's also the approach that related projects like Chumsky/msdfgen have taken. As an added benefit, for use cases with purely static content like games, most of the server-side processing can be done offline as a build step.

I would like to have ports to Vulkan and D3D, but I'm not super keen on maintaining separate shaders that have to be kept in sync. I was thinking about using ANGLE to automatically compile HLSL from the GLSL, but I don't have any definite plans yet.

**Comment by duane** [comment]
This is super informative, especially explaining why you didn't go ahead with the rust native renderer.

Thanks!

**Comment by dylanede** [comment]
@pcwalton What plans do you have regarding documentation for people to be able to integrate pathfinder into applications? An overview of how the pieces fit together, even at a high level, would be very handy.
