### ISSUE TITLE
stroke path calculation seems broken in certain case

### ISSUE THREAD

**Issue by daiheitan** [pcwalton/pathfinder#57]
```xml
<path d="M63,252.1L66.1,249.4L63,246.7" stroke-width="2" stroke="#000000" fill="none"/>
```
Seems the svg demo renders wrong stroke path. Maybe pathfinder_path_utils::stroke is giving wrong endpoints in this case?

**Comment by dylanede** [comment]
I've also bumped into this. Given this SVG (uploaded as a zip since GitHub refuses to attach SVGs):

[test_svg.zip](https://github.com/pcwalton/pathfinder/files/1576188/test_svg.zip)

the following output is observed (ignore the clipped bottom of the frame):

![image](https://user-images.githubusercontent.com/10339269/34215847-8ed386a4-e59e-11e7-85b6-8a1aeeefacff.png)

The correct output should look like this (ignoring discrepancies in line joins, which pathfinder doesn't implement yet):

![image](https://user-images.githubusercontent.com/10339269/34215875-a3d0f0fa-e59e-11e7-8758-72ca42658092.png)

This SVG includes both closed and open paths. Observed issues:

* Closed paths are not actually getting the last edge added to close them
* Sometimes the right-most pair of edges in a path get badly triangulated. This doesn't seem to be affected by whether the path is created in a clockwise or anti-clockwise fashion.
* The top-left path isn't being rendered.
* All paths are exactly twice as thick as expected.

I have seen similar issues when using Pathfinder in an OpenGL ES renderer I'm working on, with much more complex graphics. The above SVG renders with identical problems in my renderer as well.

@pcwalton What are your thoughts?

**Comment by pcwalton** [comment]
Interesting, thanks for the report! I'll take a look.

**Comment by pcwalton** [comment]
I believe this is all fixed. Thanks for the bug report!

**Comment by dylanede** [comment]
I've checked out the latest commit, and although most of the problems are fixed, the top left spiral shape is still not showing up. Also, the closed black pentagon does not appear to be joining the starting edge with the last edge. This is what I see:

![image](https://user-images.githubusercontent.com/10339269/34249177-b97e4b7c-e630-11e7-9efa-9e6c77ad04d5.png)

**Comment by dylanede** [comment]
On further inspection, it appears that the spiral shape only shows up when using XCAA. Under other modes it doesn't appear.

**Comment by dylanede** [comment]
It appears that some new problems have appeared as a result of these fixes.

Before the fixes, this svg (a stroked and filled path generated from some text in Inkscape) looked like this (using XCAA):

![image](https://user-images.githubusercontent.com/10339269/34251502-41305950-e638-11e7-897b-e0c70bfe952c.png)

Now it looks like this:

![image](https://user-images.githubusercontent.com/10339269/34251621-a4244a62-e638-11e7-8a65-5d7bf1fc3c6a.png)

and with no anti-aliasing, it looks like this:

![image](https://user-images.githubusercontent.com/10339269/34251683-cd7081a6-e638-11e7-9fec-2fca8f858d3a.png)

For reference, all browsers I tried it on rendered it like this:

![image](https://user-images.githubusercontent.com/10339269/34251743-fc555726-e638-11e7-8e35-371457a271f9.png)

**Comment by pcwalton** [comment]
@dylanede Did you rebuild the demo with `npm run build`? The top left path shows up locally for me under all AA modes.

**Comment by dylanede** [comment]
Ah, it's possible that I didn't. That could explain it. When I'm back at that machine I'll check.

However with the other problem (the strokes in the "Testing" image) I have seen similar behaviour in my own renderer after updating the dependency on pathfinder, so it's not affected by changes in the client.

**Comment by daiheitan** [comment]
Seems when using the new stroke logic, every `EndPoint.subpath_index` is `0` no matter how many subpaths are there in the `PathBuffer`. Is this a bug?

**Comment by daiheitan** [comment]
Oops, it seems that I need to consume the stream once again in a new PathBuffer to make the numbers correct. Ignore my last report please
