### ISSUE TITLE
Rotation broken both for text and SVG

### ISSUE THREAD

**Issue by trishume** [pcwalton/pathfinder#65]
Rotation produces weird artifacts, see GIFs. Reproduced both in FF and Chrome, on both my Nvidia and Intel card on macOS Sierra. The SVG doubling effect is extra suspicious since it suggests the tiger is being drawn twice and fixing this bug might improve performance.

![pathfinder_rot_issue_1](https://user-images.githubusercontent.com/887610/35612874-18bbd696-061f-11e8-802c-27be53a426c1.gif)
![pathfinder_rot_issue_2](https://user-images.githubusercontent.com/887610/35612878-1b40a59a-061f-11e8-9a90-9e62b37d9c58.gif)

**Comment by mindbrix** [comment]
I'm see exactly the same on my Intel HD Graphics 615 equipped MacBook running 10.12.6

**Comment by pcwalton** [comment]
Yeah, I've been working on this this week. The problem with the SVG is that MCAA didn't support rotation. This is now fixed in 5879d9778dfea0391fd0bba54a2277e99df03afd with a complete rewrite of that approach.

I'm working on a fix for the text now.

**Comment by mindbrix** [comment]
Rotation is now fixed here. Great work.

**Comment by trishume** [comment]
Confirmed that SVG rotation is fixed now. 

Interestingly, I notice the frames take longer proportional to the rotation, increasing from 5ms at 0 degrees to 10ms at 90 degrees back down to 5 at 180 degrees. Also the trackpad transforms are applied in the wrong order so rotating causes panning to be messed up.

Also the 2nd lower whisker on the right away from the nose appears to flicker in length while zooming, but I don't know if that was always the case.

**Comment by pcwalton** [comment]
The whiskers are pretty badly stroked right now due to stroke-to-fill conversion not being recursive yet. We'll see if fixing that helps things.

There will always be some minor distortion for multicolor SVG simply due to the fact that endpoints are effectively snapped to the nearest pixel. The only way to fix this that I can see, other than overriding parts of the rasterizer pipeline using atomics, would be to use stencil-and-cover. Stencil-and-cover however removes *all* overdraw optimizations, so I'd rather take the minor distortion.

**Comment by pcwalton** [comment]
Text rotation should be fixed as of https://github.com/pcwalton/pathfinder/commit/a84b7c7cbde7383187838af8673c46fea7532411.

Let's close this and open new issues for any remaining problems.
