### ISSUE TITLE
How could I get glyph_index by char

### ISSUE THREAD

**Issue by Brooooooklyn** [pcwalton/pathfinder#66]
I'm trying to use `font_render` to render some text, but how could I get glyph_index by char?
I was tried to use [rusttype](https://docs.rs/rusttype/0.3.0/rusttype/) to parse font file and get `glyph_index` through it, but it crashed while the font file is a `Chinese Font File`.

**Comment by pcwalton** [comment]
Going from character to glyph index is called *shaping*. This is a complex task because multiple glyphs might correspond to each character in the case of international text. You should use a shaping library for this, as Pathfinder doesn't do it.

You might find rusttype meets your needs if they're simple: https://github.com/redox-os/rusttype

**Comment by pcwalton** [comment]
Closing to keep the issue list tidy, but feel free to reopen.

**Comment by Brooooooklyn** [comment]
I add these codes into `font-renderer/src/freetype/mod.rs`, and it seems to work fine.
But I don't know how to make this function work with `core_graphics` and `directwrite`.

```rust
   pub fn get_glyph_index(&mut self, font_instance: &FontInstance, ch: char)
                             -> Result<u32, ()> {
        let face = match self.faces.get(&font_instance.font_key) {
            None => panic!(),
            Some(face) => face,
        };
        unsafe {
            Ok(FT_Get_Char_Index(face.face, ch as u64))
        }
    }
```
